### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by alext64** [alext64/SEBC#1]

**Comment by alext64** [comment]
For the Bonus lab, I added 2 Internally Hosted Remote Parcel Repositories (the first two) and a Local Parcel Repository (the last one), because I was uncertain about the question.

**Comment by cfusi** [comment]
That is OK!
Please do not neglect to check also the reverse lookup.
Here you can find a reference:
https://www.cloudera.com/documentation/other/reference-architecture/topics/ra_bare_metal_deployment.html#concept_aj4_g4l_f2b
